version: '3.8'

services:
  lotrproducer:
    build:
      context: ./
      dockerfile: Dockerfile.producer
    deploy:
      replicas: 3 

  lotrconsumer:
    build:
      context: ./
      dockerfile: Dockerfile.consumer
    deploy:
      replicas: 2 


